print('>Start<')
a, b = int(input()), int(input())
print('Сложение: ', a + b)
print('Вычитание: ', a - b)
print('Умножение: ', a * b)
print('Деление с остатком:', a / b)
print('Целочисленное деление:', a // b)
print('Возведение в степень:', a ** b)
print('Остаток от деления:', a % b)
print('Модуль чисел:', abs(a), abs(b))
print('Минимальное:', min(a, b))
print('Максимальное:', max(a, b))
print('Возведение в степень с pow():', pow(a, b))
print('Тип объекта', type(a), type(b))
